### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by snowdqdzq** [WodxTV/Discord-Token-Information-Tool#1]
hello when i open it closes how to do please?

**Comment by wodxgod** [comment]
Hello, are you running it through a terminal like CMD or by doubleclicking the file?

**Comment by wodxgod** [comment]
> hello when i open it closes how to do please?

Hello, are you running it through a terminal like CMD or by doubleclicking the file?

**Comment by snowdqdzq** [comment]
doubleclicking the file

**Comment by snowdqdzq** [comment]
but you have to download something?
