### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by Karlweezer555** [WodxTV/Discord-Token-Information-Tool#11]
the readme doesnt mention what i should use to install the requirements or how to get to the directory. also, pretty new to this. can someone help me out here? do i have to install python from microsoft store or from the website itself?

**Comment by Karlweezer555** [comment]
k, update. got pip working well, when i run dti.py however, it shows the colored title for about 1 frame then the window disappears. i cant see to figure out how to install the requirements. i have "pip install -r requirements.txt" as my method of getting the requirements, and the requirements.txt file has 2 words. "colorama" and "requests" pls help

**Comment by Karlweezer555** [comment]
update 2. for the requirements, it says "already satisfied". im assuming that i successfully installed the requirements. nothings changed in dti.py pls send help

**Comment by Karlweezer555** [comment]
NVM IT WORKED LOL

**Comment by SHDOW-ss** [comment]
> 

how did you get it to work im so confused

**Comment by Karlweezer555** [comment]
> > 
> 
> how did you get it to work im so confused

Tell me what your doing and I might be able to guide you. Do you have the requirements.txt satisfied?

**Comment by bestgoodgameYt** [comment]
Everything tell me what you did to get it and fix it

**Comment by Karlweezer555** [comment]
ok i remember how. first, you must install python from the official website. then install pip. you must then install the requirements using "pip install -r requirements.txt". then, you must have a discord token. i dont remember where you have to put it, but i believe you have to make a .bat file using notepad. in the file, you must type "py dti.py (token)". obviously, you must replace (token) with the discord token.

**Comment by bestgoodgameYt** [comment]
thank you
